version: 2
jobs:
  test-consul:
    working_directory: /go/src/github.com/segmentio/coredns-plugins
    docker:
      - image: circleci/golang:1.9
    steps:
      - checkout
      - run: go get -v ./consul
      - run: go test -v -race ./consul

workflows:
  version: 2
  test:
    jobs:
      - test-consul
