version: 2
jobs:
  test-consul:
    docker:
      - image: circleci/golang:1.9
    steps:
      - checkout
      - dep: go get -v ./consul
      - run: go test -v -race ./consul

workflows:
  version: 2
  test:
    jobs:
      - test-consul
